"-----------------------------------------------
"editor for develop 
"-----------------------------------------------
set number
filetype on
filetype plugin on
filetype indent on
set history=10000
syntax on
set tabstop=4
set softtabstop=4
set expandtab
set shiftwidth=4
set showmatch
"-----------------------------------------------
"NERDTree
"-----------------------------------------------
map <F7> :NERDTreeToggle<CR>

"-----------------------------------------------
"no backup
"-----------------------------------------------
"set nobackup

"-----------------------------------------------
"Encodings
"-----------------------------------------------
"set encoding=utf-8
"set fileencoding=utf-8
let Tlist_OnlyWindow = 1
let Tlist_File_Auto_Close = 1
let Tlist_Show_One_File = 1
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_Max_Submenu_Items = 1
let Tlist_php_settings = 'php;f:function;c:class;d:constant'
map <silent> <F8> :TlistToggle<CR>
source ~/.vim/plugin/php-doc.vim 
inoremap <C-P> <ESC>:call PhpDocSingle()<CR>i 
nnoremap <C-P> :call PhpDocSingle()<CR> 
vnoremap <C-P> :call PhpDocRange()<CR>
map <C-l> :tabn<CR>
map <C-h> :tabp<CR>
map <C-t> :tabnew<CR>
